# Generated by Django 3.2.19 on 2023-06-29 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_full_name', models.CharField(max_length=50)),
                ('profile_email', models.EmailField(max_length=254)),
                ('profile_phone_number', models.CharField(max_length=20)),
                ('profile_nationality', django_countries.fields.CountryField(max_length=2)),
                ('profile_country', django_countries.fields.CountryField(max_length=2)),
                ('profile_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_town_or_city', models.CharField(max_length=40)),
                ('profile_street_address1', models.CharField(max_length=80)),
                ('profile_street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('profile_county', models.CharField(blank=True, max_length=80, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
