# Generated by Django 3.2.19 on 2023-07-06 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='message',
        ),
    ]
