# Generated by Django 3.2.19 on 2023-06-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
