# Generated by Django 3.2.19 on 2023-06-05 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_continent_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('slots', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('slots_left', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(max_length=254)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='continent',
            name='continent',
            field=models.CharField(max_length=50),
        ),
    ]
