# Generated by Django 3.2.19 on 2023-06-05 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tour_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
