# Generated by Django 3.2.19 on 2023-06-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_tour_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
