# Generated by Django 3.2.19 on 2023-06-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_continent_friendly_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='start_date',
            new_name='start',
        ),
    ]
