# Generated by Django 3.2.19 on 2023-06-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_auto_20230611_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
