# Generated by Django 3.2.19 on 2023-07-06 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_alter_tour_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['name']},
        ),
    ]
