# Generated by Django 3.2.19 on 2023-07-10 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_alter_tour_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='location',
            new_name='meeting_location',
        ),
    ]
