# Generated by Django 3.2.19 on 2023-07-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_auto_20230721_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='friendly_name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
