# Generated by Django 3.2.19 on 2023-07-30 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_alter_continent_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
