# Generated by Django 3.2.19 on 2023-06-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_remove_order_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='upon_arrival',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
