# Generated by Django 3.2.19 on 2023-06-29 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_upon_arrival'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='upon_arrival',
        ),
    ]
