# Generated by Django 3.2.19 on 2023-07-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20230706_0050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='nationality',
        ),
    ]
