# Generated by Django 3.2.19 on 2023-07-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_alter_continent_friendly_name'),
        ('checkout', '0010_auto_20230730_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='tour',
            field=models.ForeignKey(on_delete=models.SET('Tour no longer available, please contact owner for a written receipt'), to='tours.tour'),
        ),
    ]
