# Generated by Django 3.2.19 on 2023-07-30 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_alter_tour_price'),
        ('checkout', '0011_alter_orderitem_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='tour',
            field=models.ForeignKey(on_delete=models.SET(61), to='tours.tour'),
        ),
    ]
